services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mos1
    ports:
      - "1883:1883" 
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log